config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # If you want to route /admin/articles to ArticlesController (without the Admin:: module prefix), you could use:
  # scope '/admin' do
  # resources :articles, :comments
  # end
  # adds /checkout/something pointing to the same action
  scope '/checkout' do # They will all start with /checkout. There is no model.
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end

  resources :pages

  get '/static/:permalink', to: 'pages#permalink', as: 'permalink'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # get 'categories/index'
  resources :categories, only: %i[index show]

  resources :deals, only: :show
  # get 'deals/show'

  # get 'products/index'
  # get 'products/show'
  resources :products, only: %i[index show] do
    collection do
      get 'search_results'
    end
    collection do
      get 'shopping_cart'
    end
  end

  post 'products/add_to_cart/:id', to: 'products#add_to_cart', as: 'add_to_cart'

  delete 'products/remove_from_cart/:id', to: 'products#remove_from_cart', as: 'remove_from_cart'

  # get 'provinces/index'
  resources :provinces, only: :index

  # get 'customers/index'
  # get 'customers/show'
  resources :customers, only: %i[index show]

  # get 'orders/index'
  # get 'orders/show'
  resources :orders, only: %i[index show]
  get '/review_order', to: 'orders#review_order', as: 'review_order'
  get '/order_final', to: 'orders#order_final', as: 'order_final'

  # get 'payments/index'
  # get 'payments/show'
  resources :payments, only: %i[index show]

  # get 'line_items/index'
  resources :line_items

  resource :cart, only: [:show]
  post '/cart', to: 'line_items#create', as: 'update_qty'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'products#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :products
  validates :name, presence: true
end

app/models/customer.rb
# frozen_string_literal: true

class Customer < ApplicationRecord
  belongs_to :province
  has_many :orders
  validates :firstName, :lastName, presence: true
  # validates :stripeId, numericality: { only_integer: true }
  # actual association do not return all payment by customer
end

app/models/deal.rb
# frozen_string_literal: true

class Deal < ApplicationRecord
  has_many :products
  validates :name, presence: true
end

app/models/line_item.rb
# frozen_string_literal: true

class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  # validates :quantity, :unit_price, presence: true
  # validates :quantity, :unit_price, numericality: { only_decimal: true }

  before_save :set_unit_price
  before_save :set_total_price

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.sellPrice
    end
  end

  def total_price
    unit_price.to_f * quantity.to_i
  end

  private

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total_price
    self[:total_price] = quantity * set_unit_price
  end
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :customer
  has_one :payment
  has_many :line_items
  has_many :products, through: :line_items, source: :product
  accepts_nested_attributes_for :line_items, allow_destroy: true
  # validates :pstTimeOfPurchase, :gstTimeOfPurchase, presence: true
  # validates :pstTimeOfPurchase, :gstTimeOfPurchase, numericality: { only_decimal: true }

  before_save :set_subtotal
  # before_save :set_total_price

  def subtotal
    line_items.collect { |line_item| line_item.valid? ? (line_item.unit_price.to_f * line_item.quantity.to_i) : 0 }.sum
  end

  private

  def set_subtotal
    self[:subtotal] = subtotal
  end

  # def set_total_price
  #   self[:total_price] = (gstTimeOfPurchase * set_subtotal) + (pstTimeOfPurchase * set_subtotal) + set_subtotal
  # end
end

app/models/page.rb
# frozen_string_literal: true

class Page < ApplicationRecord
  validates :title, :permalink, presence: true
  validates :permalink, uniqueness: true
end

app/models/payment.rb
# frozen_string_literal: true

class Payment < ApplicationRecord
  belongs_to :order
  validates :amount, :date, presence: true
  validates :amount, numericality: { only_decimal: true }
  # actual association do not return all payments by customer
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :category
  belongs_to :deal
  has_many :line_items
  has_many :orders, through: :line_items, source: :order
  has_one_attached :image
  validates :name, :manufacturer, :sellPrice, presence: true
  validates :sellPrice, numericality: { only_decimal: true }
  paginates_per 15
end

app/models/province.rb
# frozen_string_literal: true

class Province < ApplicationRecord
  has_many :customers
  has_many :orders, through: :customers
  validates :name, :gstTax, :pstTax, presence: true
  validates :gstTax, :pstTax, numericality: { only_decimal: true }
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  def index
    @orders = Order.order(:name)
  end

  def show
    @order = Order.find(params[:id])
  end

  def review_order
    if session[:order_id].nil?
      redirect_to root_path
    else
      @order = current_order
      # Need some adjustment to include address
      assign_atr(@order).save
    end
  end

  def order_final
    if session[:order_id].nil?
      redirect_to root_path
    else
      @order = current_order

      @session = Stripe::Checkout::Session.create(
        payment_method_types: ['card'],
        line_items: [
          {
            name: 'TESTE',
            amount: 500,
            currency: 'cad',
            quantity: 2
          },
          {
            name: 'PST',
            description: 'Manitoba Provincial Sales Tax',
            amount: (500 * 7 / 100.0).round.to_i,
            currency: 'cad',
            quantity: 1
          },
          {
            name: 'GST',
            description: 'Federal Goods and Services Tax',
            amount: (500 * 5 / 100.0).round.to_i,
            currency: 'cad',
            quantity: 1
          }
        ],
        success_url: order_final_url + '?session_id={CHECKOUT_SESSION_ID}',
        cancel_url: checkout_cancel_url
      )

      # respond_to do |format|
      #   format.js # renders create.js.erb
      # end

      @order.created_at = Time.now
      @order.save
      session[:order_id] = nil
    end
  end

  private

  def assign_atr(order)
    @cust_id = session[:cust_id]
    @cust = Customer.find(@cust_id)
    order.assign_attributes(
      customer_id: @cust_id,
      pstTimeOfPurchase: @cust.province.pstTax,
      gstTimeOfPurchase: @cust.province.gstTax
    )
    order
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/views/orders/_order.html.erb
<tr>
  <td><%= order.products.count %></td>
  <td><%= order.orderStatus %></td>
  <td><%= order.pstTimeOfPurchase %></td>
  <td><%= order.gstTimeOfPurchase%></td>
</tr>

app/views/orders/index.html.erb
<h1>Orders#index</h1>
<p>Find me in app/views/orders/index.html.erb</p>
<p>
  <% @orders.each do |order| %>
    <%= link_to order.pstTimeOfPurchase, order, class: 'button is-link' %>
  <% end %>
</p>

app/views/orders/order_final.html.erb
Final Order

app/views/orders/review_order.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7">
      <h2>Shopping Cart</h2>
      <strong>Shipping Address</strong>
      <ul>
      <li><%= @order.customer.firstName  %> <%= @order.customer.lastName  %></li>
      <li><%= @order.customer.streetAddress  %></li>
      <li><%= @order.customer.city  %>,
      <%= @order.customer.province.name %> -
      <%= @order.customer.postalCode  %></li>
      <li><%= @order.customer.country %></li>
      <li>Phone: <%= @order.customer.phone %></li>
      </ul>
    </div>
    <div class="col-md-5">
      <table>
        <tbody>
          <tr>
            <td><span>Quantity of Items in Cart (<%= products_in_cart_count %>):</span></td>
            <td></td>
          </tr>
          <tr>
            <td></td>
            <td><hr></td>
          </tr>
          <tr>
            <td><span>Total before tax: </span></td>
            <td><%=number_to_currency(@order.subtotal, unit: 'CDN$ ') %></td>
          </tr>
          <tr>
            <td><span>Estimated GST/HST: </span></td>
            <td><%=number_to_currency(@order.gstTimeOfPurchase/100 * @order.subtotal, unit: 'CDN$ ') %></td>
          </tr>
          <tr>
            <td><span>Estimated PST/RST/QST: </span></td>
            <td><%=number_to_currency(@order.pstTimeOfPurchase/100 * @order.subtotal, unit: 'CDN$ ') %></td>
          </tr>
          <tr>
            <td>
                <hr>
            </td>
          </tr>
          <tr>
            <td>Order Total:</td>
            <td><%=number_to_currency(@order.gstTimeOfPurchase/100 * @order.subtotal + @order.pstTimeOfPurchase/100 * @order.subtotal + @order.subtotal, unit: 'CDN$ ') %></td>
          </tr>
          <tr><td><%= link_to  "Place your order", order_final_path, class: 'btn btn-warning' %> <%= button_to "buy now!", order_final_path, method: :post, params: { id: @order.id }, remote: true %></td></tr>
        </tbody>
      </table>

    </div>
  </div>
  <div>
    <div >
    <hr>
    <% @order.line_items.each do |li| %>
      <div  class="row">
        <div class="col-md-2">
          <%= image_tag li.product.image.variant(resize_to_limit: [90, 90]) %>
        </div>
        <div class="col-md-10">
          <div>
            <strong><%= li.product.name %></strong>
          </div>
          <div >
                <span><strong><%= number_to_currency(li.product.sellPrice, unit: 'CDN$ ') %></strong></span>
          </div>
        <div>
          <span>
            Usually ships within 6 to 10 days.
          </span>
        </div>
        <div>
          <strong>Quantity:&nbsp;</strong><span ><%= li.quantity %></span>
        </div>
        <hr>
      </div>
    </div>

    <% end %>

  </div>
</div>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>
<h2>pstTimeOfPurchase: <%= @order.pstTimeOfPurchase %></h2>
<h2>gstTimeOfPurchase: <%= @order.gstTimeOfPurchase %></h2>
<h2>orderStatus: <%= @order.orderStatus %></h2>