config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # If you want to route /admin/articles to ArticlesController (without the Admin:: module prefix), you could use:
  # scope '/admin' do
  # resources :articles, :comments
  # end
  # adds /checkout/something pointing to the same action
  scope '/checkout' do # They will all start with /checkout. There is no model.
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end

  resources :pages

  get '/static/:permalink', to: 'pages#permalink', as: 'permalink'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # get 'categories/index'
  resources :categories, only: %i[index show]

  resources :deals, only: :show
  # get 'deals/show'

  # get 'products/index'
  # get 'products/show'
  resources :products, only: %i[index show] do
    collection do
      get 'search_results'
    end
    collection do
      get 'shopping_cart'
    end
  end

  post 'products/add_to_cart/:id', to: 'products#add_to_cart', as: 'add_to_cart'

  delete 'products/remove_from_cart/:id', to: 'products#remove_from_cart', as: 'remove_from_cart'

  # get 'provinces/index'
  resources :provinces, only: :index

  # get 'customers/index'
  # get 'customers/show'
  resources :customers, only: %i[index show]

  # get 'orders/index'
  # get 'orders/show'
  resources :orders, only: %i[index show]
  get '/review_order', to: 'orders#review_order', as: 'review_order'
  get '/order_final', to: 'orders#order_final', as: 'order_final'

  # get 'payments/index'
  # get 'payments/show'
  resources :payments, only: %i[index show]

  # get 'line_items/index'
  resources :line_items

  resource :cart, only: [:show]
  post '/cart', to: 'line_items#create', as: 'update_qty'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'products#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :products
  validates :name, presence: true
end

app/models/customer.rb
# frozen_string_literal: true

class Customer < ApplicationRecord
  belongs_to :province
  has_many :orders
  validates :firstName, :lastName, presence: true
  # validates :stripeId, numericality: { only_integer: true }
  # actual association do not return all payment by customer
end

app/models/deal.rb
# frozen_string_literal: true

class Deal < ApplicationRecord
  has_many :products
  validates :name, presence: true
end

app/models/line_item.rb
# frozen_string_literal: true

class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  # validates :quantity, :unit_price, presence: true
  # validates :quantity, :unit_price, numericality: { only_decimal: true }

  before_save :set_unit_price
  before_save :set_total_price

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.sellPrice
    end
  end

  def total_price
    unit_price.to_f * quantity.to_i
  end

  private

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total_price
    self[:total_price] = quantity * set_unit_price
  end
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :customer
  has_one :payment
  has_many :line_items
  has_many :products, through: :line_items, source: :product
  accepts_nested_attributes_for :line_items, allow_destroy: true
  # validates :pstTimeOfPurchase, :gstTimeOfPurchase, presence: true
  # validates :pstTimeOfPurchase, :gstTimeOfPurchase, numericality: { only_decimal: true }

  before_save :set_subtotal
  # before_save :set_total_price

  def subtotal
    line_items.collect { |line_item| line_item.valid? ? (line_item.unit_price.to_f * line_item.quantity.to_i) : 0 }.sum
  end

  private

  def set_subtotal
    self[:subtotal] = subtotal
  end

  # def set_total_price
  #   self[:total_price] = (gstTimeOfPurchase * set_subtotal) + (pstTimeOfPurchase * set_subtotal) + set_subtotal
  # end
end

app/models/page.rb
# frozen_string_literal: true

class Page < ApplicationRecord
  validates :title, :permalink, presence: true
  validates :permalink, uniqueness: true
end

app/models/payment.rb
# frozen_string_literal: true

class Payment < ApplicationRecord
  belongs_to :order
  validates :amount, :date, presence: true
  validates :amount, numericality: { only_decimal: true }
  # actual association do not return all payments by customer
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :category
  belongs_to :deal
  has_many :line_items
  has_many :orders, through: :line_items, source: :order
  has_one_attached :image
  validates :name, :manufacturer, :sellPrice, presence: true
  validates :sellPrice, numericality: { only_decimal: true }
  paginates_per 15
end

app/models/province.rb
# frozen_string_literal: true

class Province < ApplicationRecord
  has_many :customers
  has_many :orders, through: :customers
  validates :name, :gstTax, :pstTax, presence: true
  validates :gstTax, :pstTax, numericality: { only_decimal: true }
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  def show
    # Once again we access the current_order to determine the line_items for the customer's order.
    @line_items = current_order.line_items
    @line_item = current_order.line_items.new
    @cart_items = Product.find(session[:cart])
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/views/carts/_cart_item.html.erb
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>
<%=  debug session[:order_id] %>
<%=  debug session[:cust] %>

<% if !@order_item.nil? && @order_item.errors.any? %>
	<ul>
		<% @order_item.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>

<% if @line_items.size>0 %>
	<% @line_items.each do |item| %>
		<div class="well">
			<div class="row">
				<div class="col-sm-8">
					<h3><%= item.product.name %></h3>
				</div>
				<div class="col-sm-4">
					<div class="pull-right">
					<%= form_for @line_item, url: update_qty_path do |f| %>
						<%= f.hidden_field :product_id, value: item.product.id %>
						<%= f.hidden_field :update_cart, value: true %>
						<h5><%= number_to_currency (item.product.sellPrice) %></h5>
						<div class="form-group">
							<%= f.text_field :quantity, value: item.quantity.to_i, min: 1, class: 'form-control' %>
						</div>
						<div class="btn-group">
							<%= f.submit "Update Quantity", class: 'btn btn-primary' %>
							<%= link_to "Delete", item, method: :delete, remote: true, class: 'btn btn-danger'  %>
						</div>
						<span>Total Price: <%= number_to_currency (item.total_price) %></span>

					<% end %>
          <br>
          <br>
					</div>
				</div>
			</div>
		</div>
	<% end %>
	<%= link_to "Review Order", review_order_path, class:"button is-success" %>
<% else %>
	<p>No items in this cart.</p>
<% end %>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>












<% if @line_items.any? %>
  <% @line_items.each do |item| %>
    <p><%= item.product.name %> | <%= link_to "Delete", item, method: :delete, remote: true, class: 'btn btn-danger' %></p>
    <p> Unit Price: <%= number_to_currency item.product.sellPrice %> | Quantity: <%= item.quantity %> | Total Price: <%= number_to_currency (item.product.sellPrice * item.quantity) %></p>
  <% end %>

<% else %>
  <p>Your shopping cart is empty.</p>
<% end %>
<br>
<br>
<br>
<br>
Below is from Kyle tutorial
<br>
<br>
<% @cart_items.each_with_index do |my_id, index|%>
<p><%= @cart_items[index].name %></p>
<% end %>


app/views/carts/show.html.erb
<div class="cart_item">
	<%= render "carts/cart_item" %>
</div>