config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # If you want to route /admin/articles to ArticlesController (without the Admin:: module prefix), you could use:
  # scope '/admin' do
  # resources :articles, :comments
  # end
  # adds /checkout/something pointing to the same action
  scope '/checkout' do # They will all start with /checkout. There is no model.
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end

  resources :pages

  get '/static/:permalink', to: 'pages#permalink', as: 'permalink'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # get 'categories/index'
  resources :categories, only: %i[index show]

  resources :deals, only: :show
  # get 'deals/show'

  # get 'products/index'
  # get 'products/show'
  resources :products, only: %i[index show] do
    collection do
      get 'search_results'
    end
    collection do
      get 'shopping_cart'
    end
  end

  post 'products/add_to_cart/:id', to: 'products#add_to_cart', as: 'add_to_cart'

  delete 'products/remove_from_cart/:id', to: 'products#remove_from_cart', as: 'remove_from_cart'

  # get 'provinces/index'
  resources :provinces, only: :index

  # get 'customers/index'
  # get 'customers/show'
  resources :customers, only: %i[index show]

  # get 'orders/index'
  # get 'orders/show'
  resources :orders, only: %i[index show]
  get '/review_order', to: 'orders#review_order', as: 'review_order'
  get '/order_final', to: 'orders#order_final', as: 'order_final'

  # get 'payments/index'
  # get 'payments/show'
  resources :payments, only: %i[index show]

  # get 'line_items/index'
  resources :line_items

  resource :cart, only: [:show]
  post '/cart', to: 'line_items#create', as: 'update_qty'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'products#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :products
  validates :name, presence: true
end

app/models/customer.rb
# frozen_string_literal: true

class Customer < ApplicationRecord
  belongs_to :province
  has_many :orders
  validates :firstName, :lastName, presence: true
  # validates :stripeId, numericality: { only_integer: true }
  # actual association do not return all payment by customer
end

app/models/deal.rb
# frozen_string_literal: true

class Deal < ApplicationRecord
  has_many :products
  validates :name, presence: true
end

app/models/line_item.rb
# frozen_string_literal: true

class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  # validates :quantity, :unit_price, presence: true
  # validates :quantity, :unit_price, numericality: { only_decimal: true }

  before_save :set_unit_price
  before_save :set_total_price

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.sellPrice
    end
  end

  def total_price
    unit_price.to_f * quantity.to_i
  end

  private

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total_price
    self[:total_price] = quantity * set_unit_price
  end
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :customer
  has_one :payment
  has_many :line_items
  has_many :products, through: :line_items, source: :product
  accepts_nested_attributes_for :line_items, allow_destroy: true
  # validates :pstTimeOfPurchase, :gstTimeOfPurchase, presence: true
  # validates :pstTimeOfPurchase, :gstTimeOfPurchase, numericality: { only_decimal: true }

  before_save :set_subtotal
  # before_save :set_total_price

  def subtotal
    line_items.collect { |line_item| line_item.valid? ? (line_item.unit_price.to_f * line_item.quantity.to_i) : 0 }.sum
  end

  private

  def set_subtotal
    self[:subtotal] = subtotal
  end

  # def set_total_price
  #   self[:total_price] = (gstTimeOfPurchase * set_subtotal) + (pstTimeOfPurchase * set_subtotal) + set_subtotal
  # end
end

app/models/page.rb
# frozen_string_literal: true

class Page < ApplicationRecord
  validates :title, :permalink, presence: true
  validates :permalink, uniqueness: true
end

app/models/payment.rb
# frozen_string_literal: true

class Payment < ApplicationRecord
  belongs_to :order
  validates :amount, :date, presence: true
  validates :amount, numericality: { only_decimal: true }
  # actual association do not return all payments by customer
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :category
  belongs_to :deal
  has_many :line_items
  has_many :orders, through: :line_items, source: :order
  has_one_attached :image
  validates :name, :manufacturer, :sellPrice, presence: true
  validates :sellPrice, numericality: { only_decimal: true }
  paginates_per 15
end

app/models/province.rb
# frozen_string_literal: true

class Province < ApplicationRecord
  has_many :customers
  has_many :orders, through: :customers
  validates :name, :gstTax, :pstTax, presence: true
  validates :gstTax, :pstTax, numericality: { only_decimal: true }
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/views/layouts/_cart.html.erb
<%= link_to "#{current_order.line_items.size} items / price #{number_to_currency (current_order.subtotal)}", cart_path%>
<%= link_to cart_path do %>
<span><%= image_tag "logos/shopping_cart-24px.svg", height: '30', alt: 'Shopping Cart' %></span>
<span><%= products_in_cart_count %></span>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar is-warning is-spaced" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="https://bulma.io">
      <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item">
        <%= link_to "Home", root_path, class: "navbar-item" %>
      </a>
      <a class="navbar-item">
        <%= link_to "About Us", permalink_path(permalink: 'about_us'), class: "navbar-item" %>
      </a>
       <a class="navbar-item">
        <%= link_to "Contact Us", permalink_path(permalink: 'contact_us'), class: "navbar-item" %>
      </a>

    <div class="navbar-item has-dropdown is-hoverable">
      <a class="navbar-link">
        Offers
      </a>
        <div class="navbar-dropdown">
            <a class="navbar-item">
              <%= link_to "On Sale", deal_path(2), class: "navbar-item" %>
            </a>
            <a class="navbar-item">
              <%= link_to "New Release", deal_path(1), class: "navbar-item" %>
            </a>
            <a class="navbar-item">
              <%= link_to "Regular Price", deal_path(3), class: "navbar-item" %>
            </a>
          </div>
    </div>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Categories
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item">
            <%= link_to "Computers & Tablets", category_path(203), class:"navbar-item" %>
          </a>
          <a class="navbar-item">
            <%= link_to "Musical Instruments", category_path(202), class:"navbar-item" %>
          </a>
          <a class="navbar-item">
            <%= link_to "Smart Home & Car Electronics", category_path(204), class:"navbar-item" %>
          </a>
          <a class="navbar-item">
            <%= link_to "TV & Home Theatre", category_path(201), class:"navbar-item" %>
          </a>
          <a class="navbar-item">
            <%= link_to "Video Games & Movies", category_path(205), class:"navbar-item" %>
          </a>
        </div>
      </div>

    </div>
    <div class="navbar-end">
    <div >
      <%= form_with(url: search_results_products_path, method: "get", local: true) do %>
        <%= label_tag(:query, "Search for:") %>
        <%= text_field_tag(:query) %>
        <%= select_tag :category, options_from_collection_for_select(Category.all, 'id', 'name'), include_blank: "Select Category" %>
        <%= submit_tag("Search") %>
      <% end %>
    </div>
      <div class="navbar-item">
        <div class="buttons">
          <a class="button is-primary">
            <strong>Sign up</strong>
          </a>
          <a class="button is-light">
            Log in
          </a>
          <div class="button is-info">
           <%= render 'layouts/cart' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>


app/views/layouts/_sidebar.html.erb
<aside class="menu is-hidden-touch">
  <p class="menu-label">
    Categories
  </p>
  <ul class="menu-list">
    <li><a><%= link_to "Computers & Tablets", category_path(203) %></a></li>
    <li><a><%= link_to "Musical Instruments", category_path(202) %></a></li>
    <li><a><%= link_to "Smart Home & Car Electronics", category_path(204) %></a></li>
    <li><a><%= link_to "TV & Home Theatre", category_path(201) %></a></li>
    <li><a><%= link_to "Video Games & Movies", category_path(205) %></a></li>
  </ul>
  <p class="menu-label">
    Current Offers
  </p>
  <ul class="menu-list">
    <li><a><%= link_to "On Sale", deal_path(2) %></a></li>
    <li><a><%= link_to "New Release", deal_path(1) %></a></li>
    <li><a><%= link_to "Regular Price", deal_path(3) %></a></li>

  </ul>
  <p class="menu-label">
    Transactions
  </p>
  <ul class="menu-list">
    <li><a>Payments</a></li>
    <li><a>Transfers</a></li>
    <li><a>Balance</a></li>
  </ul>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcommerceWebsite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://js.stripe.com/v3/"></script>
  </head>

  <body>
    <section class="section">
      <%= render 'layouts/navigation'%>

    </section>

    <section class="section">
    <div class=".container-fluid">
      <div class="row">
        <div class="col-2">
          <%= render 'layouts/sidebar'%>
        </div>
        <div class="col-10">
          <%= yield %>
        </div>
      </div>
    </div>
    </section>
  </body>
</html>